In [1]:
# Import dependencies
import json
import pandas as pd
import numpy as np
# built-in Python module for regular expressions
import re

In [2]:
# Import the Wikipedia JSON file
file_dir = 'C://Users/elleg/Documents/GitHub/Movies-ETL/'

# Open the file using a with statement
# Note: Use the file_dir variable with an f string to get the file and
# set the mode to "r" (read).
# Then, use json.load() to convert the data to a list of dictionaries.
with open(f'{file_dir}/wikipedia-movies.json', mode='r') as file:
    wiki_movies_raw = json.load(file)

In [3]:
# Get the number of records
len(wiki_movies_raw)

7311

In [4]:
# First 5 records
wiki_movies_raw[:5]

[{'url': 'https://en.wikipedia.org/wiki/The_Adventures_of_Ford_Fairlane',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0098987/',
  'title': 'The Adventures of Ford Fairlane',
  'Directed by': 'Renny Harlin',
  'Produced by': ['Steve Perry', 'Joel Silver'],
  'Screenplay by': ['David Arnott', 'James Cappe', 'Daniel Waters'],
  'Story by': ['David Arnott', 'James Cappe'],
  'Based on': ['Characters', 'by Rex Weiner'],
  'Starring': ['Andrew Dice Clay',
   'Wayne Newton',
   'Priscilla Presley',
   'Lauren Holly',
   'Morris Day',
   'Robert Englund',
   "Ed O'Neill"],
  'Narrated by': 'Andrew "Dice" Clay',
  'Music by': ['Cliff Eidelman', 'Yello'],
  'Cinematography': 'Oliver Wood',
  'Edited by': 'Michael Tronick',
  'Productioncompany ': 'Silver Pictures',
  'Distributed by': '20th Century Fox',
  'Release date': ['July 11, 1990', '(', '1990-07-11', ')'],
  'Running time': '102 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$20 million',
  'Box office': '$21.4 million'},
 {'url': 'https://en.wikipedia.org/wiki/After_Dark,_My_Sweet',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0098994/',
  'title': 'After Dark, My Sweet',
  'Directed by': 'James Foley',
  'Produced by': ['Ric Kidney', 'Robert Redlin'],
  'Screenplay by': ['James Foley', 'Robert Redlin'],
  'Based on': ['the novel', 'After Dark, My Sweet', 'by', 'Jim Thompson'],
  'Starring': ['Jason Patric',
   'Rachel Ward',
   'Bruce Dern',
   'George Dickerson'],
  'Music by': 'Maurice Jarre',
  'Cinematography': 'Mark Plummer',
  'Edited by': 'Howard E. Smith',
  'Productioncompany ': 'Avenue Pictures',
  'Distributed by': 'Avenue Pictures',
  'Release date': ['May 17, 1990',
   '(',
   '1990-05-17',
   ')',
   '(Cannes Film Market)',
   'August 24, 1990',
   '(',
   '1990-08-24',
   ')',
   '(United States)'],
  'Running time': '114 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$6 million',
  'Box office': '$2.7 million'},
 {'url': 'https://en.wikipedia.org/wiki/Air_America_(film)',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0099005/',
  'title': 'Air America',
  'Directed by': 'Roger Spottiswoode',
  'Produced by': 'Daniel Melnick',
  'Screenplay by': ['John Eskow', 'Richard Rush'],
  'Based on': ['Air America', 'by', 'Christopher Robbins'],
  'Starring': ['Mel Gibson',
   'Robert Downey Jr.',
   'Nancy Travis',
   'David Marshall Grant',
   'Lane Smith'],
  'Music by': 'Charles Gross',
  'Cinematography': 'Roger Deakins',
  'Edited by': ['John Bloom', 'Lois Freeman-Fox'],
  'Productioncompany ': ['Carolco Pictures', 'IndieProd Company'],
  'Distributed by': 'TriStar Pictures',
  'Release date': ['August 10, 1990', '(', '1990-08-10', ')'],
  'Running time': '113 minutes',
  'Country': 'United States',
  'Language': ['English', 'Lao'],
  'Budget': '$35 million',
  'Box office': '$57,718,089'},
 {'url': 'https://en.wikipedia.org/wiki/Alice_(1990_film)',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0099012/',
  'title': 'Alice',
  'Directed by': 'Woody Allen',
  'Produced by': 'Robert Greenhut',
  'Written by': 'Woody Allen',
  'Starring': ['Alec Baldwin',
   'Blythe Danner',
   'Judy Davis',
   'Mia Farrow',
   'William Hurt',
   'Keye Luke',
   'Joe Mantegna',
   'Bernadette Peters'],
  'Cinematography': 'Carlo Di Palma',
  'Edited by': 'Susan E. Morse',
  'Distributed by': 'Orion Pictures',
  'Release date': ['December 25, 1990', '(', '1990-12-25', ')'],
  'Running time': '106 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$12 million',
  'Box office': '$7,331,647'},
 {'url': 'https://en.wikipedia.org/wiki/Almost_an_Angel',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0099018/',
  'title': 'Almost an Angel',
  'Directed by': 'John Cornell',
  'Produced by': 'John Cornell',
  'Written by': 'Paul Hogan',
  'Starring': ['Paul Hogan', 'Elias Koteas', 'Linda Kozlowski'],
  'Music by': 'Maurice Jarre',
  'Cinematography': 'Russell Boyd',
  'Edited by': 'David Stiven',
  'Distributed by': 'Paramount Pictures',
  'Release date': 'December 19, 1990',
  'Running time': '95 minutes',
  'Country': 'US',
  'Language': 'English',
  'Budget': '$25 million',
  'Box office': '$6,939,946 (USA)'}]

In [5]:
# Last 5 records
wiki_movies_raw[-5:]

[{'url': 'https://en.wikipedia.org/wiki/Holmes_%26_Watson',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt1255919/',
  'title': 'Holmes & Watson',
  'Directed by': 'Etan Cohen',
  'Produced by': ['Will Ferrell',
   'Adam McKay',
   'Jimmy Miller',
   'Clayton Townsend'],
  'Screenplay by': 'Etan Cohen',
  'Based on': ['Sherlock Holmes',
   'and',
   'Dr. Watson',
   'by',
   'Sir Arthur Conan Doyle'],
  'Starring': ['Will Ferrell',
   'John C. Reilly',
   'Rebecca Hall',
   'Rob Brydon',
   'Steve Coogan',
   'Ralph Fiennes'],
  'Music by': 'Mark Mothersbaugh',
  'Cinematography': 'Oliver Wood',
  'Edited by': 'Dean Zimmerman',
  'Productioncompanies ': ['Columbia Pictures',
   'Gary Sanchez Productions',
   'Mosaic Media Group',
   'Mimran Schur Pictures'],
  'Distributed by': 'Sony Pictures Releasing',
  'Release date': ['December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '90 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$42 million',
  'Box office': '$41.9 million'},
 {'url': 'https://en.wikipedia.org/wiki/Vice_(2018_film)',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt6266538/',
  'title': 'Vice',
  'Directed by': 'Adam McKay',
  'Produced by': ['Brad Pitt',
   'Dede Gardner',
   'Jeremy Kleiner',
   'Kevin J. Messick',
   'Will Ferrell',
   'Adam McKay'],
  'Written by': 'Adam McKay',
  'Starring': ['Christian Bale',
   'Amy Adams',
   'Steve Carell',
   'Sam Rockwell',
   'Tyler Perry',
   'Alison Pill',
   'Lily Rabe',
   'Jesse Plemons'],
  'Music by': 'Nicholas Britell',
  'Cinematography': 'Greig Fraser',
  'Edited by': 'Hank Corwin',
  'Productioncompany ': ['Plan B Entertainment',
   'Gary Sanchez Productions',
   'Annapurna Pictures'],
  'Distributed by': 'Mirror Releasing',
  'Release date': ['December 11, 2018',
   '(',
   '2018-12-11',
   ')',
   '(',
   'Samuel Goldwyn Theater',
   ')',
   'December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '132 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$60 million',
  'Box office': '$76.1 million'},
 {'url': 'https://en.wikipedia.org/wiki/On_the_Basis_of_Sex',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt4669788/',
  'title': 'On the Basis of Sex',
  'Directed by': 'Mimi Leder',
  'Produced by': 'Robert W. Cort',
  'Written by': 'Daniel Stiepleman',
  'Starring': ['Felicity Jones',
   'Armie Hammer',
   'Justin Theroux',
   'Sam Waterston',
   'Kathy Bates'],
  'Music by': 'Mychael Danna',
  'Cinematography': 'Michael Grady',
  'Edited by': 'Michelle Tesoro',
  'Productioncompanies ': ['Focus Features',
   '[1]',
   'Participant Media',
   '[1]',
   'Robert Cort Productions',
   '[1]',
   'Alibaba Pictures',
   '[2]'],
  'Distributed by': 'Focus Features',
  'Release date': ['November 8, 2018',
   '(',
   '2018-11-08',
   ')',
   '(',
   'AFI Fest',
   ')',
   'December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '120 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$20 million',
  'Box office': '$38.4 million'},
 {'url': 'https://en.wikipedia.org/wiki/Destroyer_(2018_film)',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt7137380/',
  'title': 'Destroyer',
  'Directed by': 'Karyn Kusama',
  'Produced by': ['Fred Berger', 'Phil Hay', 'Matt Manfredi'],
  'Written by': ['Phil Hay', 'Matt Manfredi'],
  'Starring': ['Nicole Kidman',
   'Sebastian Stan',
   'Toby Kebbell',
   'Tatiana Maslany',
   'Bradley Whitford',
   'Jade Pettyjohn',
   'Scoot McNairy'],
  'Music by': 'Theodore Shapiro',
  'Cinematography': 'Julie Kirkwood',
  'Edited by': 'Plummy Tucker',
  'Productioncompany ': ['30West',
   'Automatik Entertainment',
   'Annapurna Pictures'],
  'Distributed by': 'Mirror Releasing',
  'Release date': ['August 31, 2018',
   '(',
   '2018-08-31',
   ')',
   '(',
   'Telluride',
   ')',
   'December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '123 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$9 million',
  'Box office': '$5.5 million'},
 {'url': 'https://en.wikipedia.org/wiki/Black_Mirror:_Bandersnatch',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt9495224/',
  'title': 'Bandersnatch',
  'Directed by': 'David Slade',
  'Produced by': 'Russell McLean',
  'Written by': 'Charlie Brooker',
  'Starring': ['Fionn Whitehead',
   'Will Poulter',
   'Craig Parkinson',
   'Alice Lowe',
   'Asim Chaudhry'],
  'Music by': 'Brian Reitzell',
  'Cinematography': ['Aaron Morton', 'Jake Polonsky'],
  'Edited by': 'Tony Kearns',
  'Productioncompany ': ['House of Tomorrow', 'Netflix'],
  'Distributed by': 'Netflix',
  'Release date': ['28 December 2018', '(', '2018-12-28', ')'],
  'Running time': 'Variable; 90 minutes for default path',
  'Country': 'United Kingdom',
  'Language': 'English'}]

In [6]:
# Some records in the middle
wiki_movies_raw[3600:3605]

[{'url': 'https://en.wikipedia.org/wiki/Benji:_Off_the_Leash!',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0315273/',
  'title': 'Benji: Off the Leash!',
  'Directed by': 'Joe Camp',
  'Written by': 'Joe Camp',
  'Starring': ['Benji', 'Nick Whitaker', 'Shaggy', 'Gypsy the Cockatoo'],
  'Music by': 'Antonio di Lorenzo',
  'Productioncompany ': 'Mulberry Square Productions',
  'Distributed by': 'Mulberry Square Productions',
  'Release date': ['March 26, 2004', '(', '2004-03-26', ')'],
  'Running time': '97 min',
  'Country': 'United States',
  'Language': 'English',
  'Box office': '$3,817,362'},
 {'url': 'https://en.wikipedia.org/wiki/The_Best_Thief_in_the_World',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0389796/',
  'title': 'The Best Thief in the World',
  'Directed by': 'Jacob Kornbluth',
  'Produced by': ['Tim Perrell', 'Nicola Usborne'],
  'Written by': 'Jacob Kornbluth',
  'Starring': ['Marc Rozendaal',
   'Michael Silverman',
   'David Warshofsky',
   'Audra McDonald',
   'Lois Smith'],
  'Music by': ['Prince Paul', 'and', 'Don Newkirk'],
  'Cinematography': 'Ben Kutchins',
  'Edited by': 'Stephanie Sterner',
  'Distributed by': 'Showtime Networks',
  'Release date': ['January 16, 2004', '(', '2004-01-16', ')'],
  'Running time': '93 minutes',
  'Country': 'United States',
  'Language': 'English'},
 {'url': 'https://en.wikipedia.org/wiki/Beyond_the_Sea_(2004_film)',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0363473/',
  'title': 'Beyond the Sea',
  'Directed by': 'Kevin Spacey',
  'Produced by': ['Kevin Spacey',
   'Phillip Barry',
   'Dana Brunetti',
   'Arthur Friedman',
   'Jan Fantl',
   'Andy Paterson'],
  'Written by': ['Lewis Colick', 'Kevin Spacey'],
  'Starring': ['Kevin Spacey', 'Kate Bosworth', 'Bob Hoskins', 'John Goodman'],
  'Music by': 'Bobby Darin',
  'Cinematography': 'Eduardo Serra',
  'Edited by': 'Trevor Waite',
  'Productioncompany ': 'Trigger Street Productions',
  'Distributed by': ['Lionsgate Films',
   '(USA)',
   'Entertainment Film Distributors',
   '(UK)',
   'GAGA',
   '(Japan)',
   'Maple Pictures',
   '(Canada)'],
  'Release date': ['December 17, 2004', '(', '2004-12-17', ')'],
  'Running time': '118 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$25 million',
  'Box office': '$8.4 million'},
 {'url': 'https://en.wikipedia.org/wiki/The_Big_Bounce_(2004_film)',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0315824/',
  'title': 'The Big Bounce',
  'Directed by': 'George Armitage',
  'Produced by': ['George Armitage', 'Steve Bing'],
  'Screenplay by': 'Sebastian Gutierrez',
  'Based on': ['The Big Bounce', 'by', 'Elmore Leonard'],
  'Starring': ['Owen Wilson',
   'Charlie Sheen',
   'Morgan Freeman',
   'Sara Foster',
   'Gary Sinise'],
  'Music by': 'George S. Clinton',
  'Cinematography': 'Jeffrey L. Kimball',
  'Edited by': 'Barry Malkin',
  'Productioncompany ': 'Shangri-La Entertainment',
  'Distributed by': 'Warner Bros. Pictures',
  'Release date': ['January 30, 2004', '(', '2004-01-30', ')'],
  'Running time': '88 minutes',
  'Language': 'English',
  'Budget': '$50 million',
  'Box office': '$6.8 million'},
 {'url': 'https://en.wikipedia.org/wiki/Birth_(film)',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0337876/',
  'title': 'Birth',
  'Directed by': 'Jonathan Glazer',
  'Produced by': ['Lizie Gower', 'Nick Morris', 'Jean-Louis Piel'],
  'Written by': ['Jean-Claude Carrière', 'Milo Addica', 'Jonathan Glazer'],
  'Starring': ['Nicole Kidman',
   'Cameron Bright',
   'Danny Huston',
   'Lauren Bacall'],
  'Music by': 'Alexandre Desplat',
  'Cinematography': 'Harris Savides',
  'Edited by': ['Sam Sneade', 'Claus Wehlisch'],
  'Distributed by': 'New Line Cinema',
  'Release date': ['November 8, 2004', '(', '2004-11-08', ')'],
  'Running time': '96 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$20 million',
  'Box office': '$23.9 million'}]

In [7]:
# Convert wikipedia movies data to a DataFrame
wiki_movies_df = pd.DataFrame(wiki_movies_raw)
wiki_movies_df.head()

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990.0,https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,Renny Harlin,"[Steve Perry, Joel Silver]","[David Arnott, James Cappe, Daniel Waters]","[David Arnott, James Cappe]","[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990.0,https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet",James Foley,"[Ric Kidney, Robert Redlin]","[James Foley, Robert Redlin]",NaN,"[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://en.wikipedia.org/wiki/Air_America_(film),1990.0,https://www.imdb.com/title/tt0099005/,Air America,Roger Spottiswoode,Daniel Melnick,"[John Eskow, Richard Rush]",NaN,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990.0,https://www.imdb.com/title/tt0099012/,Alice,Woody Allen,Robert Greenhut,NaN,NaN,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990.0,https://www.imdb.com/title/tt0099018/,Almost an Angel,John Cornell,John Cornell,NaN,NaN,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Convert the columns to a list to see them all
# (many are irrelevant to our needs)
wiki_movies_df.columns.tolist()

['url',
 'year',
 'imdb_link',
 'title',
 'Directed by',
 'Produced by',
 'Screenplay by',
 'Story by',
 'Based on',
 'Starring',
 'Narrated by',
 'Music by',
 'Cinematography',
 'Edited by',
 'Productioncompany ',
 'Distributed by',
 'Release date',
 'Running time',
 'Country',
 'Language',
 'Budget',
 'Box office',
 'Written by',
 'Genre',
 'Theme music composer',
 'Country of origin',
 'Original language(s)',
 'Producer(s)',
 'Editor(s)',
 'Production company(s)',
 'Original network',
 'Original release',
 'Productioncompanies ',
 'Executive producer(s)',
 'Production location(s)',
 'Distributor',
 'Picture format',
 'Audio format',
 'Voices of',
 'Followed by',
 'Composer(s)',
 'Created by',
 'Also known as',
 'Opening theme',
 'No. of episodes',
 'Preceded by',
 'Author',
 'Publisher',
 'Publication date',
 'Media type',
 'Pages',
 'ISBN',
 'OCLC',
 'LC Class',
 'Cover artist',
 'Series',
 'Set in',
 'Adaptation by',
 'Suggested by',
 'Biographical data',
 'Born',
 'Died',
 'Resting place',
 'Occupation',
 'Years active',
 'Spouse(s)',
 'Children',
 'Parent(s)',
 'Genres',
 'Instruments',
 'Labels',
 'Website',
 'Traditional',
 'Mandarin',
 'Type',
 'Industry',
 'Fate',
 'Founded',
 'Founder',
 'Headquarters',
 'Parent',
 'Released',
 'Recorded',
 'Venue',
 'Length',
 'Label',
 'Director',
 'Producer',
 'Area',
 'Coordinates',
 'Status',
 'Opening date',
 'Closing date',
 'Replaced',
 'Replaced by',
 'Name',
 'Attraction type',
 'Music',
 'Duration',
 'Simplified Chinese',
 'Traditional Chinese',
 'Hanyu Pinyin',
 'Literal meaning',
 'Transcriptions',
 'Bopomofo',
 'Gwoyeu Romatzyh',
 'Wade–Giles',
 'IPA',
 'Yale Romanization',
 'Jyutping',
 'Hokkien POJ',
 'Animation by',
 'Color process',
 'Engine(s)',
 'Genre(s)',
 'Actor control',
 'Production company',
 'Release(s)',
 'Format(s)',
 'Simplified',
 'Characters',
 'Date premiered',
 'Place premiered',
 'Setting',
 'Original language',
 'Subject',
 'Published',
 'Dewey Decimal',
 'Text',
 'Illustrator',
 'Original title',
 'Published in English',
 'French',
 'Developed by',
 'Ending theme',
 'No. of seasons',
 'Nationality',
 'Portrayed by',
 'Alias',
 'Species',
 'Gender',
 'Family',
 'Alma mater',
 'Camera setup',
 'Novel(s)',
 'Comics',
 'Film(s)',
 'Screen story by',
 'Hangul',
 'Revised Romanization',
 'McCune–Reischauer',
 'Developer(s)',
 'Publisher(s)',
 'Designer(s)',
 'Programmer(s)',
 'Artist(s)',
 'Writer(s)',
 'Engine',
 'Platform(s)',
 'Release',
 'Mode(s)',
 'Original work',
 'Television series',
 'Japanese',
 'Hepburn',
 'Literally',
 'Cantonese',
 'Full name',
 'Height',
 'Seasons',
 'Chinese',
 'Other names',
 'Relatives',
 'Yiddish',
 'Formerly',
 'Key people',
 'Total assets',
 'Owner',
 'Number of employees',
 'Divisions',
 'Subsidiaries',
 'Arabic',
 'Romanized',
 'Predecessor',
 'Founders',
 'Area served',
 'Products',
 'Services',
 'Russian',
 'Hebrew',
 'Revenue',
 'Operating income',
 'Polish']

In [9]:
# Filtering the data using list comprehension
wiki_movies = [movie for movie in wiki_movies_raw
              if ('Director' in movie or 'Directed by' in movie)
              and 'imdb_link' in movie]
len(wiki_movies)

7080

In [10]:
# Create a DataFrame 
wiki_filtered_df = pd.DataFrame(wiki_movies)
wiki_filtered_df.head()

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Hepburn,Literally,Cantonese,Chinese,Yiddish,Arabic,Romanized,Russian,Hebrew,Polish
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990,https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,Renny Harlin,"[Steve Perry, Joel Silver]","[David Arnott, James Cappe, Daniel Waters]","[David Arnott, James Cappe]","[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990,https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet",James Foley,"[Ric Kidney, Robert Redlin]","[James Foley, Robert Redlin]",NaN,"[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://en.wikipedia.org/wiki/Air_America_(film),1990,https://www.imdb.com/title/tt0099005/,Air America,Roger Spottiswoode,Daniel Melnick,"[John Eskow, Richard Rush]",NaN,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990,https://www.imdb.com/title/tt0099012/,Alice,Woody Allen,Robert Greenhut,NaN,NaN,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990,https://www.imdb.com/title/tt0099018/,Almost an Angel,John Cornell,John Cornell,NaN,NaN,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Adding 'No. of Episodes' to list comprehension
wiki_movies = [movie for movie in wiki_movies_raw
              if ('Director' in movie or 'Directed by' in movie)
              and 'imdb_link' in movie
              and 'No. of episodes' not in movie]
len(wiki_movies)

7076

In [12]:
# Create another DataFrame 
wiki_filtered2_df = pd.DataFrame(wiki_movies)
wiki_filtered2_df.head()

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Hepburn,Literally,Cantonese,Chinese,Yiddish,Arabic,Romanized,Russian,Hebrew,Polish
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990,https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,Renny Harlin,"[Steve Perry, Joel Silver]","[David Arnott, James Cappe, Daniel Waters]","[David Arnott, James Cappe]","[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990,https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet",James Foley,"[Ric Kidney, Robert Redlin]","[James Foley, Robert Redlin]",NaN,"[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://en.wikipedia.org/wiki/Air_America_(film),1990,https://www.imdb.com/title/tt0099005/,Air America,Roger Spottiswoode,Daniel Melnick,"[John Eskow, Richard Rush]",NaN,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990,https://www.imdb.com/title/tt0099012/,Alice,Woody Allen,Robert Greenhut,NaN,NaN,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990,https://www.imdb.com/title/tt0099018/,Almost an Angel,John Cornell,John Cornell,NaN,NaN,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# Look for movies in Arabic language
wiki_filtered2_df[wiki_filtered2_df['Arabic'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Hepburn,Literally,Cantonese,Chinese,Yiddish,Arabic,Romanized,Russian,Hebrew,Polish
6834,https://en.wikipedia.org/wiki/The_Insult_(film),2018,https://www.imdb.com/title/tt7048622/,The Insult,Ziad Doueiri,"[Rachid Bouchareb, Jean Bréhat, Julie Gayet, A...",NaN,NaN,NaN,"[Adel Karam, Kamel El Basha]",...,NaN,Case No. 23,NaN,NaN,NaN,قضية رقم ٢٣,Qadiyya raqm 23,NaN,NaN,NaN
7058,https://en.wikipedia.org/wiki/Capernaum_(film),2018,https://www.imdb.com/title/tt8267604/,Capernaum,Nadine Labaki,"[Michel Merkt, Khaled Mouzanar]","[Nadine Labaki, Jihad Hojaily, Michelle Keserw...","[Georges Khabbaz, Nadine Labaki, Michelle Kese...",NaN,"[Zain Al Rafeea, Yordanos Shiferaw, Boluwatife...",...,NaN,NaN,NaN,NaN,NaN,کفرناحوم‎,NaN,NaN,NaN,NaN

In [14]:
# Get the urls for the Arabic movies
wiki_filtered2_df[wiki_filtered2_df['Arabic'].notnull()]['url']

6834    https://en.wikipedia.org/wiki/The_Insult_(film)
7058     https://en.wikipedia.org/wiki/Capernaum_(film)
Name: url, dtype: object

Looks like the different languages are alternate titles for the movie. Combine all of the alternate titles into one dictionary.

In [15]:
# Go through the columns and determine which are alternate titles.

sorted(wiki_filtered2_df.columns.tolist())

['Adaptation by',
 'Also known as',
 'Animation by',
 'Arabic',
 'Audio format',
 'Based on',
 'Box office',
 'Budget',
 'Cantonese',
 'Chinese',
 'Cinematography',
 'Color process',
 'Composer(s)',
 'Country',
 'Country of origin',
 'Created by',
 'Directed by',
 'Director',
 'Distributed by',
 'Distributor',
 'Edited by',
 'Editor(s)',
 'Executive producer(s)',
 'Followed by',
 'French',
 'Genre',
 'Hangul',
 'Hebrew',
 'Hepburn',
 'Japanese',
 'Label',
 'Language',
 'Length',
 'Literally',
 'Mandarin',
 'McCune–Reischauer',
 'Music by',
 'Narrated by',
 'Original language(s)',
 'Original network',
 'Original release',
 'Original title',
 'Picture format',
 'Polish',
 'Preceded by',
 'Produced by',
 'Producer',
 'Producer(s)',
 'Production company(s)',
 'Production location(s)',
 'Productioncompanies ',
 'Productioncompany ',
 'Recorded',
 'Release date',
 'Released',
 'Revised Romanization',
 'Romanized',
 'Running time',
 'Russian',
 'Screen story by',
 'Screenplay by',
 'Simplified',
 'Starring',
 'Story by',
 'Suggested by',
 'Theme music composer',
 'Traditional',
 'Venue',
 'Voices of',
 'Written by',
 'Yiddish',
 'imdb_link',
 'title',
 'url',
 'year']

The value_counts() method is a quick, easy way to see what non-null values there are in a column.

In [16]:
# Check for non-null values in Polish column.
wiki_filtered2_df.value_counts('Polish')

Polish
Zimna wojna    1
dtype: int64

In [17]:
# Write a simple function to make a copy of the movie and return it.
# The function is "clean_movie" and "movie" is the parameter.
def clean_movie(movie):
    # Because the movies are dicts and we want to make non-destructive edits,
    # make a copy of the movie.
    # When we pass movie as a parameter to the dict() constructor, it reserves
    # a new space in memory and copies all of the info in movie to that new space.
    movie = dict(movie) # create a non-destructive copy
    # Inside of the function, we can create a new local variable called movie
    # and assign it the new copy of the parameter movie. This way, inside of
    # the clean_movie() function, movie will refer to the local copy. Any
    # changes we make inside clean_movie() will now only affect the copy, so
    # if we make a mistake, we still have the original, untouched movie to reference.
    
    # Now we can add in code to handle the alternative titles. The logic we need to implement follows:
    # 1. Make an empty dict to hold all of the alternative titles.
    alt_titles = {}
    # 2. Loop through a list of all alternative title keys:
    for key in ['Also known as', 'Arabic', 'Cantonese', 'Chinese', 'French',
               'Hangul', 'Hebrew', 'Hepburn', 'Japanese', 'Literally',
               'Mandarin', 'McCune-Reischauer', 'Original title', 'Polish',
               'Revised Romanization', 'Romanized', 'Russian',
               'Simplified', 'Traditional', 'Yiddish']:
        # Check if the current key exists in the movie object.
        if key in movie:
             # If so, remove the key-value pair and add to the alternative titles dict.
            alt_titles[key] = movie[key]
            # Hint: To remove a key-value pair from a dict in Python, use the pop() method.
            movie.pop(key)
    # 3. After looping through every key, add the alternative titles dict to the movie object.
    if len(alt_titles) > 0:
        movie['alt_titles'] = alt_titles
        
    return movie

In [18]:
# Make a list of clean movies with a list comprehension.
clean_movies = [clean_movie(movie) for movie in wiki_movies]

In [19]:
# Set wiki_movies_df to be the DataFrame created from clean_movies
wiki_movies_df = pd.DataFrame(clean_movies)

# Print out a list of the columns.
sorted(wiki_movies_df.columns.tolist())

['Adaptation by',
 'Animation by',
 'Audio format',
 'Based on',
 'Box office',
 'Budget',
 'Cinematography',
 'Color process',
 'Composer(s)',
 'Country',
 'Country of origin',
 'Created by',
 'Directed by',
 'Director',
 'Distributed by',
 'Distributor',
 'Edited by',
 'Editor(s)',
 'Executive producer(s)',
 'Followed by',
 'Genre',
 'Label',
 'Language',
 'Length',
 'McCune–Reischauer',
 'Music by',
 'Narrated by',
 'Original language(s)',
 'Original network',
 'Original release',
 'Picture format',
 'Preceded by',
 'Produced by',
 'Producer',
 'Producer(s)',
 'Production company(s)',
 'Production location(s)',
 'Productioncompanies ',
 'Productioncompany ',
 'Recorded',
 'Release date',
 'Released',
 'Running time',
 'Screen story by',
 'Screenplay by',
 'Starring',
 'Story by',
 'Suggested by',
 'Theme music composer',
 'Venue',
 'Voices of',
 'Written by',
 'alt_titles',
 'imdb_link',
 'title',
 'url',
 'year']

We need to consolidate columns with the same data into one column. We can use the pop() method to change the name of a dictionary key, because pop() returns the value from the removed key-value pair. We have to check if the key exists in a given movie record, so it will be helpful to make a small function inside clean_movie().

NOTE: It's perfectly fine to define a function within another function. In fact, it's often preferable. Functions that are defined within another function live within the scope of the first equation. This means that the inner function can only be called inside the outer function. Outside the original function, it's impossible to call the inner function.

In [20]:
# Create a nested function to consolidate the related "director" columns
# This new function will go within the clean_movie() function

def clean_movie(movie):
    
    movie = dict(movie) # create a non-destructive copy

    alt_titles = {}
    
    # combine alternate titles into one list
  
    for key in ['Also known as', 'Arabic', 'Cantonese', 'Chinese', 'French',
               'Hangul', 'Hebrew', 'Hepburn', 'Japanese', 'Literally',
               'Mandarin', 'McCune-Reischauer', 'Original title', 'Polish',
               'Revised Romanization', 'Romanized', 'Russian',
               'Simplified', 'Traditional', 'Yiddish']:
       
        if key in movie:            
            alt_titles[key] = movie[key]
            movie.pop(key)
            
    if len(alt_titles) > 0:
        movie['alt_titles'] = alt_titles
        
    # Merge similar column names
    def change_column_name(old_name, new_name):
        if old_name in movie:
            movie[new_name] = movie.pop(old_name)
            
    change_column_name('Adaptation by', 'Writer(s)')
    change_column_name('Country of origin', 'Country')
    change_column_name('Directed by', 'Director')
    change_column_name('Distributed by', 'Distributor')
    change_column_name('Edited by', 'Editor(s)')
    change_column_name('Length', 'Running time')
    change_column_name('Music by', 'Composer(s)')
    change_column_name('Original release', 'Release date')
    change_column_name('Produced by', 'Producer(s)')
    change_column_name('Producer', 'Producer(s)')
    change_column_name('Productioncompanies ', 'Production company(s)')
    change_column_name('Productioncompany ', 'Production company(s)')
    change_column_name('Released', 'Release date')
    change_column_name('Screen story by', 'Writer(s)')
    change_column_name('Screenplay by', 'Writer(s)')
    change_column_name('Story by', 'Writer(s)')
    change_column_name('Theme music composer', 'Composer(s)')
    change_column_name('Written by', 'Writer(s)')
    
    
        
    return movie

clean_movies = [clean_movie(movie) for movie in wiki_movies]

wiki_movies_df = pd.DataFrame(clean_movies)

sorted(wiki_movies_df.columns.tolist())

['Animation by',
 'Audio format',
 'Based on',
 'Box office',
 'Budget',
 'Cinematography',
 'Color process',
 'Composer(s)',
 'Country',
 'Created by',
 'Director',
 'Distributor',
 'Editor(s)',
 'Executive producer(s)',
 'Followed by',
 'Genre',
 'Label',
 'Language',
 'McCune–Reischauer',
 'Narrated by',
 'Original language(s)',
 'Original network',
 'Picture format',
 'Preceded by',
 'Producer(s)',
 'Production company(s)',
 'Production location(s)',
 'Recorded',
 'Release date',
 'Running time',
 'Starring',
 'Suggested by',
 'Venue',
 'Voices of',
 'Writer(s)',
 'alt_titles',
 'imdb_link',
 'title',
 'url',
 'year']

## Removing Duplicate Rows
Use IMDb ID to merge with the Kaggle data, but we want to make sure we don't have any duplicate rows. First, we need to extract the IMDb ID from the IMDb link. To do this, we need to learn regular expressions.

IMPORTANT
Regular expressions, also known as regex, are strings of characters that define a search pattern. While the syntax might be new, this is a concept you're already familiar with in the noncoding world.

For example, "MM/DD/YYYY" is a string of characters that defines a pattern for entering dates. You could say it's a regular expression that you can easily recognize because it follows a well-defined pattern. In the same way, "(###) ###-####" is a pattern for entering U.S. phone numbers. Regular expressions are just a more formal way of defining these kinds of patterns so that our code can find them. We'll expand on regular expressions in a later section. For now, just remember that they're used to search for patterns in text.

First, we'll use regular expressions in Pandas' built-in string methods that work on a Series object accessed with the str property. We'll be using str.extract(), which takes in a regular expression pattern. IMDb links generally look like "https://www.imdb.com/title/tt1234567/," with "tt1234567" as the IMDb ID. The regular expression for a group of characters that start with "tt" and has seven digits is "(tt\d{7})".

+ "(tt\d{7})" — The parentheses marks say to look for one group of text.
+ "(tt\d{7})" — The "tt" in the string simply says to match two lowercase Ts.
+ "(tt\d{7})" — The "\d" says to match a numerical digit.
+ "(tt\d{7})" — The "{7}" says to match the last thing (numerical digits) exactly seven times.

Since regular expressions use backslashes, which Python also uses for special characters, we want to tell Python to treat our regular expression characters as a raw string of text. Therefore, we put an r before the quotes. We need to do this every time we create a regular expression string. We’ll put the extracted IMDB ID into a new column. Altogether, the code to extract the IMDb ID looks like the following:

wiki_movies_df['imdb_id'] = wiki_movies_df['imdb_link'].str.extract(r'(tt\d{7})')

## Execute The Code
Now we can drop any duplicates of IMDb IDs by using the drop_duplicates() method. To specify that we only want to consider the IMDb ID, use the subset argument, and set inplace equal to True so that the operation is performed on the selected dataframe. Otherwise, the operation would return an edited dataframe that would need to be saved to a new variable. We also want to see the new number of rows and how many rows were dropped. The whole cell should look like the following:

In [21]:
# Drop the duplicate values and determine the new number of rows.
wiki_movies_df['imdb_id'] = wiki_movies_df['imdb_link'].str.extract(r'(tt\d{7})')
print(len(wiki_movies_df))
wiki_movies_df.drop_duplicates(subset='imdb_id', inplace=True)
print(len(wiki_movies_df))
wiki_movies_df.head()

7076
7033

,url,year,imdb_link,title,Based on,Starring,Narrated by,Cinematography,Release date,Running time,...,Preceded by,Suggested by,alt_titles,Recorded,Venue,Label,Animation by,Color process,McCune–Reischauer,imdb_id
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990,https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,"[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...","Andrew ""Dice"" Clay",Oliver Wood,"[July 11, 1990, (, 1990-07-11, )]",102 minutes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0098987
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990,https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet","[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",NaN,Mark Plummer,"[May 17, 1990, (, 1990-05-17, ), (Cannes Film ...",114 minutes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0098994
2,https://en.wikipedia.org/wiki/Air_America_(film),1990,https://www.imdb.com/title/tt0099005/,Air America,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",NaN,Roger Deakins,"[August 10, 1990, (, 1990-08-10, )]",113 minutes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0099005
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990,https://www.imdb.com/title/tt0099012/,Alice,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",NaN,Carlo Di Palma,"[December 25, 1990, (, 1990-12-25, )]",106 minutes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0099012
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990,https://www.imdb.com/title/tt0099018/,Almost an Angel,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",NaN,Russell Boyd,"December 19, 1990",95 minutes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0099018

## Remove Mostly Null Columns
Now that we've consolidated redundant columns, we want to see which columns don't contain much useful data. Since this is scraped data, it's possible many columns are mostly null.

One way to get the count of null values for each column is to use a list comprehension, as shown below:

[[column,wiki_movies_df[column].isnull().sum()] for column in wiki_movies_df.columns]

You could also use a for loop and a print statement.

Either way, we can see about half the columns have more than 6,000 null values. We could remove them by hand, but it's better to do it programmatically to make sure we don't miss any. Let's make a list of columns that have less than 90% null values and use those to trim down our dataset.

Tweak the above list comprehension:
[column for column in wiki_movies_df.columns if wiki_movies_df[column].isnull().sum() < len(wiki_movies_df) * 0.9]

That will give us the columns that we want to keep, which we can select from our Pandas DataFrame as follows:

In [22]:
# Remove the columns with mostly null values (more than 90%)
wiki_columns_to_keep = [column for column in wiki_movies_df.columns if wiki_movies_df[column].isnull().sum() < len(wiki_movies_df) * 0.9]
wiki_movies_df = wiki_movies_df[wiki_columns_to_keep]
wiki_movies_df.head()

,url,year,imdb_link,title,Based on,Starring,Cinematography,Release date,Running time,Country,...,Budget,Box office,Director,Distributor,Editor(s),Composer(s),Producer(s),Production company(s),Writer(s),imdb_id
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990,https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,"[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...",Oliver Wood,"[July 11, 1990, (, 1990-07-11, )]",102 minutes,United States,...,$20 million,$21.4 million,Renny Harlin,20th Century Fox,Michael Tronick,"[Cliff Eidelman, Yello]","[Steve Perry, Joel Silver]",Silver Pictures,"[David Arnott, James Cappe]",tt0098987
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990,https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet","[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",Mark Plummer,"[May 17, 1990, (, 1990-05-17, ), (Cannes Film ...",114 minutes,United States,...,$6 million,$2.7 million,James Foley,Avenue Pictures,Howard E. Smith,Maurice Jarre,"[Ric Kidney, Robert Redlin]",Avenue Pictures,"[James Foley, Robert Redlin]",tt0098994
2,https://en.wikipedia.org/wiki/Air_America_(film),1990,https://www.imdb.com/title/tt0099005/,Air America,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",Roger Deakins,"[August 10, 1990, (, 1990-08-10, )]",113 minutes,United States,...,$35 million,"$57,718,089",Roger Spottiswoode,TriStar Pictures,"[John Bloom, Lois Freeman-Fox]",Charles Gross,Daniel Melnick,"[Carolco Pictures, IndieProd Company]","[John Eskow, Richard Rush]",tt0099005
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990,https://www.imdb.com/title/tt0099012/,Alice,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",Carlo Di Palma,"[December 25, 1990, (, 1990-12-25, )]",106 minutes,United States,...,$12 million,"$7,331,647",Woody Allen,Orion Pictures,Susan E. Morse,NaN,Robert Greenhut,NaN,Woody Allen,tt0099012
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990,https://www.imdb.com/title/tt0099018/,Almost an Angel,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",Russell Boyd,"December 19, 1990",95 minutes,US,...,$25 million,"$6,939,946 (USA)",John Cornell,Paramount Pictures,David Stiven,Maurice Jarre,John Cornell,NaN,Paul Hogan,tt0099018

## Make a Plan to Convert and Parse the Data
We've got our DataFrame columns trimmed down to just the ones we want, but some of the columns have data stored as text when it should be a different data type, such as numeric data or datetimes. To convert those columns, we need to understand how to use regular expressions.

Regular expressions are ridiculously powerful, but they can be intimidating at first. There are even seasoned programmers who still don't feel entirely comfortable with regular expressions, but don't worry. We'll break down each step, and before you know it, you'll be rocking regular expressions like a pro.

First, we need to identify which columns need to be converted. wiki_movies_df.dtypes will display the data type for each column.

The apply function takes and applies another function to every single value of a Pandas series. Looking through the data, column by column, we see that:

+ Box office should be numeric.
+ Budget should be numeric.
+ Release date should be a date object.
+ Running time should be numeric.

The box office and budget amounts aren't written in a consistent style, so we're going to need a powerful way to parse their data correctly. We've already dipped a toe into regular expressions; now it's time to dive all the way in.

We'll start on the box office data, which should give us code that we can reuse and tweak for the budget data since they're both currencies. It will be helpful to only look at rows where box office data is defined, so first we'll make a data series that drops missing values with the following:

In [23]:
# Make a data series that drops the missing values.
box_office = wiki_movies_df['Box office'].dropna()

# As a habit, always check the number of data points that exist after
# you drop any data.

len(box_office)

5485

In [24]:
# Regular expressions only work on strings, so we'll need to make sure
# all of the box office data is entered as a string. By using the map()
# method, we can see which values are not strings.
# First, make a is_not_a_string() function:

def is_not_a_string(x):
    return type(x) != str

box_office[box_office.map(is_not_a_string)]

34                           [US$, 4,212,828]
54      [$6,698,361 (, United States, ), [2]]
74                    [$6,488,144, (US), [1]]
126                [US$1,531,489, (domestic)]
130                          [US$, 4,803,039]
                        ...
6980               [$99.6, million, [4], [5]]
6994                   [$365.6, million, [1]]
6995                         [$53.8, million]
7015                     [$435, million, [7]]
7048                   [$529.3, million, [4]]
Name: Box office, Length: 135, dtype: object

Having to create a new function every time we want to use the map() method is cumbersome and interrupts the readability of our code. What we want is a stripped-down, one-line way of writing our functions. Also, we don't need to use it ever again outside of our map() call, so we don't need to give it a name. If you think we're talking about types of functions that will work here, you're right.

REWIND
Remember, this is what lambda functions are made for. Instead of creating a new function with a block of code and the def keyword, we can create an anonymous lambda function right inside the map() call.

Remember, lambda functions don't have a name (because they don't need one) and automatically return a variable. They use the following syntax:

lambda arguments: expression

So the lambda function version of is_not_a_string() is:

lambda x: type(x) != str

In [25]:
# We can update our map() call to use the lambda function directly instead
# of using is_not_a_string():

box_office[box_office.map(lambda x: type(x) != str)]

34                           [US$, 4,212,828]
54      [$6,698,361 (, United States, ), [2]]
74                    [$6,488,144, (US), [1]]
126                [US$1,531,489, (domestic)]
130                          [US$, 4,803,039]
                        ...
6980               [$99.6, million, [4], [5]]
6994                   [$365.6, million, [1]]
6995                         [$53.8, million]
7015                     [$435, million, [7]]
7048                   [$529.3, million, [4]]
Name: Box office, Length: 135, dtype: object

From the output, we can see that there are quite a few data points that are stored as lists. There is a join() string method that concatenates list items into one string; however, we can't just type join(some_list) because the join() method belongs to string objects. We need to make a separator string and then call the join() method on it. For example, the code would be:

some_list = ['One','Two','Three']
'Mississippi'.join(some_list)

The outputs would be:

'OneMississippiTwoMississippiThree'

In [26]:
# We'll use a simple space as our joining character and apply the join()
# function only when our data points are lists. The code looks like the following:

box_office = box_office.apply(lambda x: ' '.join(x) if type(x) == list else x)

# Looking through the data, many of the box office numbers are written
# either like "\$123.4 million" (or billion) or "\$123,456,789." We'll
# use regular expressions to find out just how many of each style are
# in our data.

# There is a built-in Python module for regular expressions: re. We'll
# need to import that library, so add the line below to the first cell,
# with the other import statements, and rerun the cell.

box_office.sample(n=20)

6177     $427,418 (US)
6764      $7.2 million
859      $12.7 million
6738    $700.4 million
4994     $31.1 million
6967          $244,331
2372     $41.1 million
5503      $3.6 million
5719     $24.2 million
5928           $14,752
2459      $3.1 million
3788     $96.9 million
6402       $18 million
5601     $73.1 million
133        $14 million
2204          $166,082
4462     $138,814 (US)
807      $54,207 (USA)
5681      $4.4 million
720           $296,081
Name: Box office, dtype: object

# Write Regular Expressions

Regular expressions are just strings of characters that are used as a search pattern. They are used to test if strings are in a specific format or contain a substring in a specific format, to extract pertinent information from strings while discarding unnecessary information, and to perform complicated replacements of substrings.

Regular expressions are used in almost all general-purpose languages like Python. For example, they are also used in JavaScript, C#, and Java. Sometimes they are the only viable solution to a problem.

Each character in a regular expression serves a purpose, based on what kind of character it is. We'll break down the different character types and the purposes they serve.

## Literal Characters
Literal characters are the simplest character class. A regular expression made of literal characters will match any string that contains the expression as a substring. For example, if we made a regular expression of the string "cat" and used it to search for any matches in another string—"The tomcat was placated with the catch of the day"—it would match three times: "The tomcat was placated with the catch of the day."

However, regular expressions also have special characters that make it much more powerful than just finding a substring. We've already used the special character \d to find any digit from 0 to 9.

NOTE
You might be thinking, "But \d is two characters!" You're not wrong. It is written with two characters. However, backslashes in strings have a long history of being used to write special characters that would be difficult to enter directly.

For example, there is a character in ASCII and Unicode for creating a new line (it's aptly named "newline character"). However, adding it to a string is difficult to do, so we write \n inside the string, which Python converts to the newline character. Regular expressions also treat character combinations that start with a backslash as one character, so it's fine to refer to them as a single character.

## Character Types: \d, \w, \s (and \D, \W, \S)
As we've seen, \d is a special character that matches any digit from 0 to 9. There are other special characters like \d. The full list is:

\d will match any digit from 0 to 9.
\D will match any non-digit character.
\w matches a word character (a letter, digit, or underscore).
\W matches any non-word character (anything other than a letter, digit, or underscore, such as spaces and punctuation).
\s will match any whitespace character (including spaces, tabs, and newlines).
\S will match any non-whitespace characters.

## Character Sets: [ ]
If we need to be more specific than digits, alphanumeric characters, or whitespace characters, we can use the square brackets to define a character set. For example, "[ceh]at" would match '"cat", "eat", "hat", and "that", but not "rat."

We can also specify ranges of characters inside a character set. For example:

"[a-z]" matches any lowercase letter.
"[A-Z]" matches any uppercase character.
"[0-9]" matches any digit.
We can include multiple ranges, so:

"[a-zA-Z]" matches any lowercase or uppercase letter.
"[a-zA-Z0-9]" matches any alphanumeric character.
But, we can also have smaller ranges, such as:

"[A-E]"would match "A", "B", "C", "D", or "E".
"[1-3]" would match the digits "1", "2", or "3".

## Match (Almost) Everything: .
The period, or dot (.), is a wildcard in regular expressions, which means it will match any single character whether it is a digit, a letter, whitespace, or punctuation. The only thing that a dot won't match is a line break (remember, line breaks are also stored as characters). In Python's regular expression module, there's an option to make the dot match every character, including line breaks.

## Escaping: \
The dot and square brackets are examples of metacharacters in regular expressions. Metacharacters are like the superheroes in a regular expression because they have powers like "match everything" or "create a character set."

But what if we need metacharacters to act like ordinary literal characters? For example, if we use the regular expression "ca.," the dot will match any character, so "cat", "car", "cab", "ca!", "ca?", and "ca." would all be matches.

What if we want to specifically search for only "ca." with an actual period? The period by itself in a regular expression is being a superhero, matching everything. So when we want it to act like just a literal character, we need to give it a secret identity. We use the backslash "\" to do this. The backslash tells the parser to treat the upcoming metacharacter like a literal character. So, "ca\." will only match "ca.". Strings such as "cat", "car", and "cab", and the others from above won't be matched.

The backslash in a regular expression is called the escape character. It says that the next character gets to escape its duties as a special character in the regular expression and act like a plain old literal character. We'll meet more superpowered metacharacters, such as curly brackets, parentheses, and plus signs. If we want to match text that has curly brackets, parentheses, or plus signs, we'll use the backslash to treat these superpowered metacharacters like literal characters.

## Special Counting Characters: *, +, {}, ?
There are also special counting characters that specify how many times a character can show up.

The first counting character is the asterisk: *.In regular expressions, the asterisk says the previous character can repeat any number of times, including zero. So, "ca*t" would match "cat" and "caaat" but also "fiction." If we want to specify that the character has to show up at least once, we use the plus sign: +. So, "ca+t" would match "cat" and "caaat" but not "fiction."

If we want to search for a character that shows up an exact number of times, we use the curly brackets: { }. When we extracted the IMDb IDs, we wanted IDs that had exactly seven digits, or "\d{7}". We can also put two numbers in curly brackets, and that would match for any number of digits within that range. So, "ca{3}t" wouldn't match "cat" or "fiction" but would match "caaat." "ca{3,5}t" would match "caaat", "caaaat", and "caaaaat" but not "cat" or "caaaaaat."

Finally, the question mark can be considered a counting character as well. The question mark is for optional characters, which means they can show up zero or one time. So, "ca?t" is equivalent to the regular expression pattern "ca{0,1}t".

## Alternation: |
If we want to search for a given string or a different string, we use the alternation character, or pipe: |. This essentially functions as a logical OR. For example, if we wanted to match "cat" or "mouse" or "dog," we would make a string "cat|mouse|dog."

## String Boundaries: ^ and $

If we need to make sure that our expression matches only at the beginning or ending of the string, we use the caret (^) to represent the beginning of the string, and the dollar sign ($) to represent the end of the string. So, "^cat" would match "cat" and "catatonic," but not "concatenate." "cat$" would also match "cat" and "tomcat," but not "catatonic."

By themselves, the string boundaries represent zero length matches; in other words, they don't match any actual characters themselves, just the boundaries of the string being searched.

## Capture Groups: ( )
Grouping in regular expressions serves two purposes. First, groups can be used to add structure to a search pattern. For example, "1,000", "1,000,000", and "1,000,000,000" as strings all have a similar structure. There is a comma followed by three zeros that repeats as a group. We can match all of these with one regular expression, using parentheses to create a capture group. One regular expression that matches all three strings would be "1(,000)+."

The second purpose for grouping is hinted at in the name "capture group." Capture groups are how regular expressions define what information should be extracted.

For example, when we needed to extract IMDb IDs from the links, we put the entire expression inside brackets. This can also be helpful when you need to make sure a long string matches a certain format, but you only need a substring inside of it.

For example, "\d{3}-\d{3}-\d{4}" would match any phone number in the form "333-333-4444," but if you wanted to extract only the digits, you would use "(\d{3})-(\d{3})-(\d{4})", and only the digits would be captured. Specifically, the digits of the phone number would be captured into three groups: area code, prefix, and line number.

## Non-Capturing Groups and Negative Lookahead Groups: (?: ), (?! )
We can modify the behavior of a group by including a question mark after the opening parenthesis. The first modification is a non-capturing group, which uses a colon after the question mark. This specifies that we only want to use the grouping structure, and we do not need to capture the information.

Non-capturing groups can feel superfluous when we're using regular expressions for just matching, but they become very important when we use regular expressions for matching and replacing.

Suppose we're anonymizing a list of phone numbers of the form "333-333-4444," and we want to change the prefix to "555," like the fake phone numbers in movies. We still need to have groups in our regular expression for the area code and the four-digit line number, but we don't want to capture them—we only want to capture the prefix.

The regular expression "(?:\d{3})-(\d{3})-(?:\d{4})" will match numbers of the form "123-456-7890," but it will only capture the middle group, the prefix. For example:

"212-012-9876" matches the regular expression "(?:\d{3})-(\d{3})-(?:\d{4})", but only "012" is captured. So, if we used this regular expression to replace the captured text with "555," it would turn "212-012-9876" to "212-555-9876."
However, "012-3456" wouldn't match at all, because there's no area code. Even though the area code is in a non-capturing group, the regular expression still needs to see it before it can make a match.
Negative lookahead groups are also non-capturing groups, but they look ahead in the text and make sure a string doesn't exist after the match.

For example, imagine we have text with phone numbers still in the form "333-333-4444," but the text also contains ID numbers that are of the form "333-333-55555." The regular expression we've been using—"(\d{3})-(\d{3})-(\d{4})"—will see the first 10 numbers of the ID and recognize a match and return "333-333-5555" as if it were a phone number.

What we need is a regular expression that matches the first 10 numbers, but also checks that there isn't another digit after the phone number. We need a group that looks ahead of the rest of the regular expression, and reports back "negative" if there's some text we don't want to see.

That's a negative lookahead group. Negative lookahead groups start with a question mark and an exclamation mark. So, to make sure there are no extra digits, a negative lookahead group would be "(?!\d)". Our new regular expression is "(\d{3})-(\d{3})-(\d{4})(?!\d)":

"333-333-4444" will match.
"333-333-55555" will not.

## Parse the Box Office Data
Remember, there are two main forms the box office data is written in: "$123.4 million" (or billion), and "$123,456,789." We're going to build a regular expression for each form, and then see what forms are left over.

## Create the First Form
For the first form, our pattern match string will include six elements in the following order:

+ A dollar sign
+ An arbitrary (but non-zero) number of digits
+ An optional decimal point
+ An arbitrary (but possibly zero) number of more digits
+ A space (maybe more than one)
+ The word "million" or "billion"

We'll translate those rules into a regular expression, step by step.

Step 1: Start with a dollar sign.
The dollar sign is a special character in regular expressions, so we'll need to escape it.

Step 2: Add an arbitrary (but non-zero) number of digits.
We'll add the \d character to specify digits only, and the + modifier to capture one or more digits. Our regular expression string now appears as "\$\d+".

Step 3: Add an optional decimal point.
Remember, the decimal point is a special character, so it needs to be escaped with a backslash. Since the decimal point is optional, add a question mark modifier after it. Our regular expression string now appears as "\$\d+\.?".

Step 4: Add an arbitrary (but possibly zero) number of more digits.
Once again, we'll use the \d character to specify digits only, but now with the * modifier because there may be no more digits after the decimal point. Our regular expression string now appears as "\$\d+\.?\d*".

Step 5: Add a space (maybe more than one).
Now we're going to use the \s character to match whitespace characters. To be safe, we'll match any number of whitespace characters with the * modifier. Our regular expression string now appears as "\$\d+\.?\d*\s*".

Step 6: Add the word "million" or "billion."
Since "million" and "billion" only differ by one letter, we can match it with a character set for the first letter. We specify character sets with square brackets, so we'll add "[mb]illion" to the end of our string. Our finished regular expression string now appears as "\$\d+\.?\d*\s*[mb]illion".

In [27]:
# Create a variable form_one and set it equal to the finished regular
# expression string. Because we need the escape characters to remain,
# we need to preface the string with an r.

form_one = r'\$\d+\.?\d*\s*[mb]illion'

# Now, to count up how many box office values match our first form.
# We'll use the str.contains() method on box_office. To ignore whether
# letters are uppercase or lowercase, add an argument called flags, and
# set it equal to re.IGNORECASE or re.I. In case the data is not a
# string, we'll add the na=False argument to parse the non-string data
# to False. Finally, we can call the sum()method to count up the total
# number that return True. Your code should look like the following:

box_office.str.contains(form_one, flags=re.IGNORECASE, na=False).sum()

3896

## Create the Second Form
Next, we'll match the numbers of our second form, "$123,456,789." In words, our pattern match string will include the following elements:

+ A dollar sign
+ A group of one to three digits
+ At least one group starting with a comma and followed by exactly three digits

Step 1: Start with a dollar sign.
Once again, we need to escape the dollar sign for it to match. Our regular expression string starts like this: "\$".

Step 2: Add a group of one to three digits.
We'll use the \d character for digits, but this time, we'll modify it with curly brackets to only match one through three repetitions. Our regular expression string now appears as "\$\d{1,3}".

Step 3: Match at least one group starting with a comma and followed by exactly three digits.
To match a comma and exactly three digits, we'll use the string ",\d{3}". To match any repetition of that group, we'll put it inside parentheses, and then put a plus sign after the parentheses: "(,\d{3})+". We'll add one more modification to specify that this is a non-capturing group by inserting a question mark and colon after the opening parenthesis: "(?:,\d{3})+". The use of a non-capturing group isn’t strictly necessary here, but it eliminates an unwanted warning message in Jupyter Notebook. Our finished regular expression string now appears as "\$\d{1,3}(?:,\d{3})+".

In [28]:
# Create another variable form_two and set it equal to the finished
# regular expression string. Don't forget to make it a raw string so
# Python keeps the escaped characters.

form_two = r'\$\d{1,3}(?:,\d{3})+'

# Now count up the number of box office values that match this pattern.
# Don't forget to put an r before the string and set the flags option to
# include re.IGNORECASE.

# Your code should look like this:

box_office.str.contains(form_two, flags=re.IGNORECASE, na=False).sum()

1544

## Compare Values in Forms
Most of the box office values are described by either form. Now we want to see which values aren't described by either. To be safe, we should see if any box office values are described by both.

To make our code easier to understand, we'll create two Boolean Series called matches_form_one and matches_form_two, and then select the box office values that don't match either. First, create the two Boolean series with the following code:

In [29]:
# Create two Boolean Series
matches_form_one = box_office.str.contains(form_one, flags=re.IGNORECASE, na=False)
matches_form_two = box_office.str.contains(form_two, flags=re.IGNORECASE, na=False)

Recall the Python logical keywords "not," "and," and "or." Try the following code to see which values in box_office don't match either form.

this will throw an error!

box_office[(not matches_form_one) and (not matches_form_two)]

The code above will give you a ValueError with the explanation "The truth value of a Series is ambiguous." (Unfortunately, the meaning of that error is also ambiguous.)

Instead, Pandas has element-wise logical operators:

+ The element-wise negation operator is the tilde: ~ (similar to "not")
+ The element-wise logical "and" is the ampersand: &
+ The element-wise logical "or" is the pipe: |

In [30]:
# The code we want to use is as follows:

box_office[~matches_form_one & ~matches_form_two]

34                         US$ 4,212,828
79                              $335.000
110                   $4.35-4.37 million
130                        US$ 4,803,039
600                           $5000 (US)
731                         $ 11,146,270
957                             $ 50,004
1070                          35,254,617
1147    $ 407,618 (U.S.) (sub-total) [1]
1446                        $ 11,829,959
1480                          £3 million
1611                            $520.000
1865                        ¥1.1 billion
2032                                 N/A
2091                                $309
2130               US$ 171.8 million [9]
2257                   US$ 3,395,581 [1]
2263            $ 1,223,034 ( domestic )
2347                            $282.175
2638            $ 104,883 (US sub-total)
2665         926,423 admissions (France)
2697      $ 1.7 million (US) (sub-total)
2823                            $414.000
2924                            $621.000
3088           $32 [2] –33.1 million [1]
3631                                 TBA
3859                  $38.9–40.3 million
3879            CN¥3.650 million (China)
4116                          £7,385,434
4123                            $161.000
4261                  $20.7–23.9 million
4306                              $20-30
4492                        $47.7 millon
4561             $45.2k (only in Turkey)
4662                USD$ 8.2 million [2]
5362                   $ 142 million [3]
5447                               £2.56
5784                            413 733$
6013                             Unknown
6145                  $17.5–18.4 million
6234                  $41.8–41.9 million
6369                               $111k
6370                                $588
6593                      less than $372
6829                    $ 41 million [3]
6843                             8 crore
6904                         $6.9 millon
Name: Box office, dtype: object

## Fix Pattern Matches

We can fix our pattern matches to capture more values by addressing these issues:

+ Some values have spaces in between the dollar sign and the number.
+ Some values use a period as a thousands separator, not a comma.
+ Some values are given as a range.
+ "Million" is sometimes misspelled as "millon."

1. Some values have spaces in between the dollar sign and the number.
This is easy to fix. Just add \s* after the dollar signs. The new forms should look like the following:

form_one = r'\$\s*\d+\.?\d*\s*[mb]illion'
form_two = r'\$\s*\d{1,3}(?:,\d{3})+'

2. Some values use a period as a thousands separator, not a comma.
This is slightly more complicated, but doable. Simply change form_two to allow for either a comma or period as a thousands separator. We’d ordinarily do that by putting the comma and period inside straight brackets [,.], but the period needs to be escaped with a slash [,\.]. The code should match the following:

form_two = r'\$\s*\d{1,3}(?:[,\.]\d{3})+'

The results will also match values like 1.234 billion, but we're trying to change raw numbers like $123.456.789. We don't want to capture any values like 1.234 billion, so we need to add a negative lookahead group that looks ahead for "million" or "billion" after the number and rejects the match if it finds those strings. Don't forget the space! The new form should look like this:

form_two = r'\$\s*\d{1,3}(?:[,\.]\d{3})+(?!\s[mb]illion)'

3. Some values are given as a range.
To solve this problem, we'll search for any string that starts with a dollar sign and ends with a hyphen, and then replace it with just a dollar sign using the replace() method. The first argument in the replace() method is the substring that will be replaced, and the second argument in the replace() method is the string to replace it with. We can use regular expressions in the first argument by sending the parameter regex=True, as shown below.

box_office = box_office.str.replace(r'\$.*[-—–](?![a-z])', '$', regex=True)

CAUTION
Always be wary of parsing dashes. The character you can type on standard keyboards is a hyphen, but some editors will convert them in certain situations to em dashes and en dashes. That is why you are seeing three different types of dashes in the regex expression above. To learn more than you've ever wanted to know about dashes, see the Wikipedia page for "Dash."  We'll need to put all three into a character set in our replace regular expression.

4. "Million" is sometimes misspelled as "millon."
This is easy enough to fix; we can just make the second "i" optional in our match string with a question mark as follows:

form_one = r'\$\s*\d+\.?\d*\s*[mb]illi?on'

The rest of the box office values make up such a small percentage of the dataset and would require too much time and effort to parse correctly, so we'll just ignore them.

We're finished writing our regular expressions for the box office values. The hard part is over. Save your work and take a quick break if you need one—you earned it!

In [31]:
# Make all changes above to fix the pattern matches.

form_one = r'\$\s*\d+\.?\d*\s*[mb]illi?on'
form_two = r'\$\s*\d{1,3}(?:[,\.]\d{3})+(?!\s[mb]illion)'

box_office = box_office.str.replace(r'\$.*[-—–](?![a-z])', '$', regex=True)

## Extract and Convert the Box Office Values
Now that we've got expressions to match almost all the box office values, we'll use them to extract only the parts of the strings that match. We do this with the str.extract() method. This method also takes in a regular expression string, but it returns a DataFrame where every column is the data that matches a capture group. We need to make a regular expression that captures data when it matches either form_one or form_two. We can do this easily with an f-string.

The f-string f'{form_one}|{form_two}' will create a regular expression that matches either form_one or form_two, so we just need to put the whole thing in parentheses to create a capture group. Our final string will be f'({form_one}|{form_two})', and the full line of code to extract the data follows:

In [32]:
# Final string to extract and convert the box office values
box_office.str.extract(f'({form_one}|{form_two})')

                  0
0     $21.4 million
1      $2.7 million
2       $57,718,089
3        $7,331,647
4        $6,939,946
...             ...
7070  $19.4 million
7071  $41.9 million
7072  $76.1 million
7073  $38.4 million
7074   $5.5 million

[5485 rows x 1 columns]

Now we need a function to turn the extracted values into a numeric value. We'll call it parse_dollars, and parse_dollars will take in a string and return a floating-point number. We'll start by making a skeleton function with comments explaining each step, and then fill in the steps with actual code.

Since we're working directly with strings, we'll use the re module to access the regular expression functions. We'll use re.match(pattern, string) to see if our string matches a pattern. To start, we'll make some small alterations to the forms we defined, splitting the million and billion matches from form one.

Next, we'll use re.sub(pattern, replacement_string, string) to remove dollar signs, spaces, commas, and letters, if necessary.

Finally, convert all the strings to floats, multiply by the right amount, and return the value.

In [33]:
def parse_dollars(s):
    # if s is not a string, return NaN
    if type(s) != str:
        return np.nan
    
    # if input is of the form $###.# million
    if re.match(r'\$\s*\d+\.?\d*\s*milli?on', s, flags=re.IGNORECASE):
        
        # remove dollar sign and " million"
        s = re.sub('\$|\s|[a-zA-Z]','', s)
        
        # convert to float and multiply by a million
        value = float(s) * 10**6

        # return value
        return value
        
    # if input is of the form $###.# billion
    elif re.match(r'\$\s*\d+\.?\d*\s*billi?on', s, flags=re.IGNORECASE):
        
        # remove dollar sign and " billion"
        s = re.sub('\$|\s|[a-zA-Z]','', s)

        # convert to float and multiply by a billion
        value = float(s) * 10**9

        # return value
        return value

    # if input is of the form $###,###,###
    elif re.match(r'\$\s*\d{1,3}(?:[,\.]\d{3})+(?!\s[mb]illion)', s, flags=re.IGNORECASE):
        
        # remove dollar sign and commas
        s = re.sub('\$|,','', s)

        # convert to float
        value = float(s)

        # return value
        return value

    # otherwise, return NaN
    else:
        return np.nan

Now we have everything we need to parse the box office values to numeric values.

First, we need to extract the values from box_office using str.extract. Then we'll apply parse_dollars to the first column in the DataFrame returned by str.extract, which in code looks like the following:

In [34]:
# extract values from box_office using str.extract
# then use parse_dollars to first column in the DataFrame returned by str.extract
wiki_movies_df['box_office'] = box_office.str.extract(f'({form_one}|{form_two})', flags=re.IGNORECASE)[0].apply(parse_dollars)
wiki_movies_df['box_office']

0       21400000.0
1        2700000.0
2       57718089.0
3        7331647.0
4        6939946.0
           ...
7071    41900000.0
7072    76100000.0
7073    38400000.0
7074     5500000.0
7075           NaN
Name: box_office, Length: 7033, dtype: float64

In [35]:
# Drop the Box Office column, as it's no longer needed.

wiki_movies_df.drop('Box office', axis=1, inplace=True)

In [36]:
wiki_movies_df['box_office']

0       21400000.0
1        2700000.0
2       57718089.0
3        7331647.0
4        6939946.0
           ...
7071    41900000.0
7072    76100000.0
7073    38400000.0
7074     5500000.0
7075           NaN
Name: box_office, Length: 7033, dtype: float64

# Parse Budget Data
Luckily, we've already done a lot of the heavy lifting for parsing the budget data when we parsed the box office data. We'll use the same pattern matches and see how many budget values are in a different form. First, we need to preprocess the budget data, just like we did for the box office data.

In [37]:
# Create a budget variable
budget = wiki_movies_df['Budget'].dropna()

# Convert any lists to strings
budget = budget.map(lambda x: ' '.join(x) if type(x) == list else x)

# Remove any values between a dollar sign and a hyphen (for budgets
# given in ranges)
budget = budget.str.replace(r'\$.*[-—–](?![a-z])', '$', regex=True)

In [38]:
# Create two Boolean Series
matches_form_one = budget.str.contains(form_one, flags=re.IGNORECASE, na=False)
matches_form_two = budget.str.contains(form_two, flags=re.IGNORECASE, na=False)

# Determine which values don't match either form
budget[~matches_form_one & ~matches_form_two]

136                         Unknown
204     60 million Norwegian Kroner
478                         Unknown
973             $34 [3] [4] million
1126               $120 [4] million
1226                        Unknown
1278                            HBO
1374                     £6,000,000
1397                     13 million
1480                   £2.8 million
1734                   CAD2,000,000
1913     PHP 85 million (estimated)
1948                    102,888,900
1953                   3,500,000 DM
1973                     ₤2,300,874
2281                     $14 milion
2451                     ₤6,350,000
3144                   € 40 million
3360               $150 [6] million
3418                        $218.32
3802                   £4.2 million
3906                            N/A
3959                    760,000 USD
4470                       19 crore
4641                    £17 million
5034              $$200 [4] million
5055           $155 [2] [3] million
5419                $40 [4] million
5424                            N/A
5447                     £4 million
5671                    €14 million
5687                   $ dead link]
6385               £ 12 million [3]
6593                     £3 million
6821                  £12.9 million
6843                      3.5 crore
6895                        919,000
7070                   €4.3 million
Name: Budget, dtype: object

In [39]:
# Remove the citation references (the numbers in square brackets)
budget = budget.str.replace(r'\[\d+\]\s*', '')
budget[~matches_form_one & ~matches_form_two]

C:\Users\elleg\AppData\Local\Temp\ipykernel_22716\758382021.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  budget = budget.str.replace(r'\[\d+\]\s*', '')

136                         Unknown
204     60 million Norwegian Kroner
478                         Unknown
973                     $34 million
1126                   $120 million
1226                        Unknown
1278                            HBO
1374                     £6,000,000
1397                     13 million
1480                   £2.8 million
1734                   CAD2,000,000
1913     PHP 85 million (estimated)
1948                    102,888,900
1953                   3,500,000 DM
1973                     ₤2,300,874
2281                     $14 milion
2451                     ₤6,350,000
3144                   € 40 million
3360                   $150 million
3418                        $218.32
3802                   £4.2 million
3906                            N/A
3959                    760,000 USD
4470                       19 crore
4641                    £17 million
5034                  $$200 million
5055                   $155 million
5419                    $40 million
5424                            N/A
5447                     £4 million
5671                    €14 million
5687                   $ dead link]
6385                  £ 12 million
6593                     £3 million
6821                  £12.9 million
6843                      3.5 crore
6895                        919,000
7070                   €4.3 million
Name: Budget, dtype: object

In [40]:
# Parse the budget values using code used to parse the box office values
wiki_movies_df['budget'] = budget.str.extract(f'({form_one}|{form_two})', flags=re.IGNORECASE)[0].apply(parse_dollars)
wiki_movies_df['budget']

0       20000000.0
1        6000000.0
2       35000000.0
3       12000000.0
4       25000000.0
           ...
7071    42000000.0
7072    60000000.0
7073    20000000.0
7074     9000000.0
7075           NaN
Name: budget, Length: 7033, dtype: float64

In [41]:
# Drop the original Budget column
wiki_movies_df.drop('Budget', axis=1, inplace=True)

## Parse Release Date
Parsing the release date will follow a similar pattern to parsing box office and budget, but with different forms.

First, make a variable that holds the non-null values of Release date in the DataFrame, converting lists to strings:

In [42]:
# Create a new variable
release_date = wiki_movies_df['Release date'].dropna().apply(lambda x: ' '.join(x) if type(x) == list else x)

The forms we'll be parsing are:

+ Full month name, one- to two-digit day, four-digit year (i.e., January 1, 2000)
+ Four-digit year, two-digit month, two-digit day, with any separator (i.e., 2000-01-01)
+ Full month name, four-digit year (i.e., January 2000)
+ Four-digit year

In [43]:
# Create four Boolean series
date_form_one = r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\s[123]?\d,\s\d{4}'
date_form_two = r'\d{4}.[01]\d.[0123]\d'
date_form_three = r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\s\d{4}'
date_form_four = r'\d{4}'

Of the four regular expressions, the first matches the month, dd, yyyy format. The second matches these two formats, for example: yyyy-mm-dd and yyyy/mm/dd. The third matches month yyyy. The fourth matches yyyy. For longer regex expressions, you might consider using the re.VERBOSE option, which allows you to comment on each component of a regex. See "How to implement a verbose REGEX in Python" on Stack Overflow for an example.

In [44]:
# Extract the dates
release_date.str.extract(f'({date_form_one}|{date_form_two}|{date_form_three}|{date_form_four})', flags=re.IGNORECASE)

                      0
0         July 11, 1990
1          May 17, 1990
2       August 10, 1990
3     December 25, 1990
4     December 19, 1990
...                 ...
7071  December 25, 2018
7072  December 11, 2018
7073   November 8, 2018
7074    August 31, 2018
7075      December 2018

[7001 rows x 1 columns]

Instead of creating our own function to parse the dates, we'll use the built-in to_datetime() method in Pandas. Since there are different date formats, set the infer_datetime_format option to True. The date formats we've targeted are among those that the to_datetime() function can recognize, which explains the infer_datetime_format=True argument below.

In [45]:
# Parse the dates using Pandas to_datetime method
wiki_movies_df['release_date'] = pd.to_datetime(release_date.str.extract(f'({date_form_one}|{date_form_two}|{date_form_three}|{date_form_four})')[0], infer_datetime_format=True)

## Parse Running Time
First, make a variable that holds the non-null values of Release date in the DataFrame, converting lists to strings:

In [46]:
# Create a variable to hold the non-null values of Release Date
running_time = wiki_movies_df['Running time'].dropna().apply(lambda x: ' '.join(x) if type(x) == list else x)
running_time

0                                 102 minutes
1                                 114 minutes
2                                 113 minutes
3                                 106 minutes
4                                  95 minutes
                        ...
7071                               90 minutes
7072                              132 minutes
7073                              120 minutes
7074                              123 minutes
7075    Variable; 90 minutes for default path
Name: Running time, Length: 6894, dtype: object

In [47]:
# Use string boundaries to see how many more fit the "100 minutes" format
running_time.str.contains(r'^\d*\s*minutes$', flags=re.IGNORECASE, na=False).sum()

6528

In [48]:
# Find out what the remaining 366 values look like
running_time[running_time.str.contains(r'^\d*\s*minutes$', flags=re.IGNORECASE, na=False) != True]

9                                                 102 min
26                                                 93 min
28                                                32 min.
34                                                101 min
35                                                 97 min
                              ...
6500       114 minutes [1] 120 minutes (extended edition)
6643                                             104 mins
6709    90 minutes (theatrical) [1] 91 minutes (unrate...
7057    108 minutes (Original cut) 98 minutes (UK cut)...
7075                Variable; 90 minutes for default path
Name: Running time, Length: 366, dtype: object

In [49]:
# Make it more general by only marking the beginning of the string and
# accepting other abbreviations of "minutes" by only searching up to
# the letter "m"

running_time.str.contains(r'^\d*\s*m', flags=re.IGNORECASE, na=False).sum()

6877

In [50]:
# Find out the remaining 17 entries
running_time[running_time.str.contains(r'^\d*\s*m', flags=re.IGNORECASE, na=False) != True]

668                     UK:84 min (DVD version) US:86 min
727                         78-102 min (depending on cut)
840                       Varies (79 [3] –84 [1] minutes)
1347                                              25 : 03
1443    United States: 77 minutes Argentina: 94 minute...
1499                                            1hr 35min
1551                                               varies
1774                    Netherlands:96 min, Canada:95 min
1777                                       approx. 14 min
2273                                           1 h 43 min
2993                                               1h 48m
3925                                              4 hours
4425    US domestic version: 86 minutes Original versi...
4967    Theatrical cut: 97 minutes Unrated cut: 107 mi...
5424                    115 [1] /123 [2] /128 [3] minutes
5447                                    1 hour 32 minutes
7075                Variable; 90 minutes for default path
Name: Running time, dtype: object

We can match all of the hour + minute patterns with one regular expression pattern. Our pattern follows:

+ Start with one or more digits.
+ Have an optional space after the digit and before the letter "h."
+ Capture all the possible abbreviations of "hour(s)." To do this, we'll make every letter in "hours" optional except the "h."
+ Have an optional space after the "hours" marker.
+ Have an optional number of digits for minutes.

As a pattern, this looks like "\d+\s*ho?u?r?s?\s*\d*".

With our new pattern, it's time to extract values. We only want to extract digits, and we want to allow for both possible patterns. Therefore, we'll add capture groups around the \d instances as well as add an alternating character. Our code will look like the following.

In [51]:
# Extract the values
running_time_extract = running_time.str.extract(r'(\d+)\s*ho?u?r?s?\s*(\d*)|(\d+)\s*m')
running_time_extract

        0    1    2
0     NaN  NaN  102
1     NaN  NaN  114
2     NaN  NaN  113
3     NaN  NaN  106
4     NaN  NaN   95
...   ...  ...  ...
7071  NaN  NaN   90
7072  NaN  NaN  132
7073  NaN  NaN  120
7074  NaN  NaN  123
7075  NaN  NaN   90

[6894 rows x 3 columns]

Unfortunately, this new DataFrame is all strings, we'll need to convert them to numeric values. Because we may have captured empty strings, we'll use the to_numeric() method and set the errors argument to 'coerce'. Coercing the errors will turn the empty strings into Not a Number (NaN), then we can use fillna() to change all the NaNs to zeros.

In [52]:
# Change NaNs to zeros and convert numbers to numeric values
running_time_extract = running_time_extract.apply(lambda col: pd.to_numeric(col, errors='coerce')).fillna(0)
running_time_extract

        0    1      2
0     0.0  0.0  102.0
1     0.0  0.0  114.0
2     0.0  0.0  113.0
3     0.0  0.0  106.0
4     0.0  0.0   95.0
...   ...  ...    ...
7071  0.0  0.0   90.0
7072  0.0  0.0  132.0
7073  0.0  0.0  120.0
7074  0.0  0.0  123.0
7075  0.0  0.0   90.0

[6894 rows x 3 columns]

Now we can apply a function that will convert the hour capture groups and minute capture groups to minutes if the pure minutes capture group is zero, and save the output to wiki_movies_df:

In [53]:
wiki_movies_df['running_time'] = running_time_extract.apply(lambda row: row[0]*60 + row[1] if row[2] == 0 else row[2], axis=1)
wiki_movies_df.head()

,url,year,imdb_link,title,Based on,Starring,Cinematography,Release date,Running time,Country,...,Editor(s),Composer(s),Producer(s),Production company(s),Writer(s),imdb_id,box_office,budget,release_date,running_time
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990,https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,"[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...",Oliver Wood,"[July 11, 1990, (, 1990-07-11, )]",102 minutes,United States,...,Michael Tronick,"[Cliff Eidelman, Yello]","[Steve Perry, Joel Silver]",Silver Pictures,"[David Arnott, James Cappe]",tt0098987,21400000.0,20000000.0,1990-07-11,102.0
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990,https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet","[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",Mark Plummer,"[May 17, 1990, (, 1990-05-17, ), (Cannes Film ...",114 minutes,United States,...,Howard E. Smith,Maurice Jarre,"[Ric Kidney, Robert Redlin]",Avenue Pictures,"[James Foley, Robert Redlin]",tt0098994,2700000.0,6000000.0,1990-05-17,114.0
2,https://en.wikipedia.org/wiki/Air_America_(film),1990,https://www.imdb.com/title/tt0099005/,Air America,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",Roger Deakins,"[August 10, 1990, (, 1990-08-10, )]",113 minutes,United States,...,"[John Bloom, Lois Freeman-Fox]",Charles Gross,Daniel Melnick,"[Carolco Pictures, IndieProd Company]","[John Eskow, Richard Rush]",tt0099005,57718089.0,35000000.0,1990-08-10,113.0
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990,https://www.imdb.com/title/tt0099012/,Alice,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",Carlo Di Palma,"[December 25, 1990, (, 1990-12-25, )]",106 minutes,United States,...,Susan E. Morse,NaN,Robert Greenhut,NaN,Woody Allen,tt0099012,7331647.0,12000000.0,1990-12-25,106.0
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990,https://www.imdb.com/title/tt0099018/,Almost an Angel,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",Russell Boyd,"December 19, 1990",95 minutes,US,...,David Stiven,Maurice Jarre,John Cornell,NaN,Paul Hogan,tt0099018,6939946.0,25000000.0,1990-12-19,95.0

In [54]:
# Drop Running Time from the dataset
wiki_movies_df.drop('Running time', axis=1, inplace=True)
wiki_movies_df.head()

,url,year,imdb_link,title,Based on,Starring,Cinematography,Release date,Country,Language,...,Editor(s),Composer(s),Producer(s),Production company(s),Writer(s),imdb_id,box_office,budget,release_date,running_time
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990,https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,"[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...",Oliver Wood,"[July 11, 1990, (, 1990-07-11, )]",United States,English,...,Michael Tronick,"[Cliff Eidelman, Yello]","[Steve Perry, Joel Silver]",Silver Pictures,"[David Arnott, James Cappe]",tt0098987,21400000.0,20000000.0,1990-07-11,102.0
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990,https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet","[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",Mark Plummer,"[May 17, 1990, (, 1990-05-17, ), (Cannes Film ...",United States,English,...,Howard E. Smith,Maurice Jarre,"[Ric Kidney, Robert Redlin]",Avenue Pictures,"[James Foley, Robert Redlin]",tt0098994,2700000.0,6000000.0,1990-05-17,114.0
2,https://en.wikipedia.org/wiki/Air_America_(film),1990,https://www.imdb.com/title/tt0099005/,Air America,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",Roger Deakins,"[August 10, 1990, (, 1990-08-10, )]",United States,"[English, Lao]",...,"[John Bloom, Lois Freeman-Fox]",Charles Gross,Daniel Melnick,"[Carolco Pictures, IndieProd Company]","[John Eskow, Richard Rush]",tt0099005,57718089.0,35000000.0,1990-08-10,113.0
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990,https://www.imdb.com/title/tt0099012/,Alice,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",Carlo Di Palma,"[December 25, 1990, (, 1990-12-25, )]",United States,English,...,Susan E. Morse,NaN,Robert Greenhut,NaN,Woody Allen,tt0099012,7331647.0,12000000.0,1990-12-25,106.0
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990,https://www.imdb.com/title/tt0099018/,Almost an Angel,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",Russell Boyd,"December 19, 1990",US,English,...,David Stiven,Maurice Jarre,John Cornell,NaN,Paul Hogan,tt0099018,6939946.0,25000000.0,1990-12-19,95.0